included:
  - Sources
  - Tests

excluded:
  - .build
  - dist
  - Resources
  - thoughts
  - .github

disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - opening_brace
  - trailing_comma
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - identifier_name
  - type_name
  - nesting
  - todo
